export type ParserStatus = "parsed" | "unsupported" | "empty" | "error";
export type AdditionalField = { label: string; value: string };
export type CostComponent = {
  label: string;
  unitPrice: number | null;
  lineTotal: number | null;
};
export type ProposalItem = {
  name: string;
  quantity: number | null;
  unit: string;
  unitPrice: number | null;
  lineTotal?: number | null;
  components?: CostComponent[];
  componentMode?: "additive" | "alternative";
  additionalFields?: AdditionalField[];
};
export type CommercialProposal = {
  title: string;
  client: string;
  clientContact: string;
  validUntil: string;
  supplier: string;
  currency: string;
  vat: string;
  discount: string;
  delivery: string;
  paymentTerms: string;
  deliveryTerms: string;
  warranty: string;
  documentNumber: string;
  documentDate: string;
  documentTotal: number | null;
  notes: string;
  items: ProposalItem[];
  additionalFields?: AdditionalField[];
};
export type FieldEvidence = {
  file: string;
  excerpt: string;
  verifiedInSource: boolean;
  page?: number;
  sheet?: string;
  block?: string;
  row?: number;
  cell?: number;
  method?: string;
  confidence?: number;
  warning?: string;
  value?: string | number;
  sourceId?: string;
  sourceMethod?: string;
  source_method?: string;
  bbox?: [number, number, number, number] | null;
  visionAgreement?: boolean | null;
  vision_agreement?: boolean | null;
  confidenceBasis?: string[];
  confidenceKind?: "heuristic";
};
export type SourceCell = {
  id: string;
  file: string;
  text: string;
  block: string;
  row: number;
  cell: number;
  page?: number | null;
  sheet?: string | null;
  kind?: "text" | "table";
  method?: string;
  column?: number;
  bbox?: [number, number, number, number] | null;
  source_method?: string;
  rowspan?: number;
  colspan?: number;
  reading_order?: number;
  vision_agreement?: boolean | null;
};
export type DocumentRouting = {
  format?: string;
  mandatory?: boolean;
  requested?: boolean;
  used?: boolean;
  available?: boolean;
  status?: "native" | "vision" | "fallback" | "limited";
  required_pages?: number[];
  processed_pages?: number[];
  reasons?: string[];
  issues?: string[];
};
export type ModelRun = {
  model: string;
  name: string;
  status: "parsed" | "error";
  durationMs: number;
  proposal?: Partial<CommercialProposal>;
  confidence: number;
  confidenceMethod?: string;
  routing?: DocumentRouting;
  error?: string;
};
export type ApiUsage = {
  inputTokens: number;
  cachedInputTokens: number;
  outputTokens: number;
  reasoningTokens: number;
  estimatedCostUsd: number | null;
  complete: boolean;
  unreportedCalls: number;
  pricingDate: string;
  calls: { stage: string; model: string; inputTokens: number; outputTokens: number; estimatedCostUsd: number | null }[];
};
export type ExtractionMetadata = {
  apiUsage?: ApiUsage;
  sourceName: string;
  parser: string;
  status: ParserStatus;
  confidence: number;
  confidenceMethod?: string;
  routing?: DocumentRouting;
  warnings: string[];
  outcome?: {
    state: "complete" | "partial" | "unavailable";
    message: string;
    unavailable: {
      field: string;
      label: string;
      reason?: "absent" | "unreadable" | "unverified";
    }[];
    ocrReviewPages?: number[];
  };
  fieldEvidence?: Record<string, FieldEvidence | FieldEvidence[]>;
  sourceCells?: SourceCell[];
  ocrPages?: number;
  ocrPageNumbers?: number[];
  ocrQuality?: { page: number; meanConfidence: number | null; words: number }[];
  cacheHit?: boolean;
  timingsMs?: { read: number; model: number; validation: number; total: number };
  modelRuns?: ModelRun[];
  verification?: {
    mode: string;
    reviewCompleted: boolean;
    visionUsed: boolean;
    coverageComplete: boolean;
    unclaimedRows: { block: string; row: number }[];
    targetedReviewRows?: number;
    issues: string[];
  };
};
export type ParseResult = {
  proposal: Partial<CommercialProposal>;
  metadata: ExtractionMetadata;
};
